CREATE TABLE `orders` (
  `id` char(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `type` int(10) unsigned NOT NULL DEFAULT 0,
  `order_status_id` int(10) unsigned NOT NULL DEFAULT 0,
  `customer_id` int(10) unsigned DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `customer_phone` varchar(50) DEFAULT NULL,
  `customer_address` varchar(500) DEFAULT NULL,
  `customer_address_latitude` decimal(10,8) DEFAULT NULL,
  `customer_address_longitude` decimal(11,8) DEFAULT NULL,
  `customer_note` text DEFAULT NULL,
  `user_vehicle_id` int(10) unsigned DEFAULT NULL,
  `vehicle_id` int(10) unsigned DEFAULT NULL,
  `vehicle_brand_name` varchar(255) DEFAULT NULL,
  `vehicle_model_name` varchar(255) DEFAULT NULL,
  `vehicle_type_name` varchar(255) DEFAULT NULL,
  `vehicle_model_year` varchar(50) DEFAULT NULL,
  `vehicle_name` varchar(255) DEFAULT NULL,
  `vehicle_image` varchar(500) DEFAULT NULL,
  `vehicle_license_plate_number` varchar(20) DEFAULT NULL,
  `mechanic_id` int(10) unsigned DEFAULT NULL,
  `mechanic_name` varchar(255) DEFAULT NULL,
  `mechanic_phone` varchar(50) DEFAULT NULL,
  `mechanic_note` text DEFAULT NULL,
  `partner_id` int(10) unsigned DEFAULT NULL,
  `partner_name` varchar(255) DEFAULT NULL,
  `workshop_id` int(10) unsigned DEFAULT NULL,
  `workshop_name` varchar(255) DEFAULT NULL,
  `workshop_address` varchar(500) DEFAULT NULL,
  `coupon_code_id` varchar(30) DEFAULT NULL,
  `partner_discount` int(10) DEFAULT NULL,
  `workshop_postal_code` varchar(255) DEFAULT NULL,
  `workshop_latitude` decimal(10,8) DEFAULT NULL,
  `workshop_longitude` decimal(11,8) DEFAULT NULL,
  `odometer` int(10) unsigned DEFAULT NULL,
  `discount` decimal(15,2) DEFAULT NULL,
  `convenience_fee` decimal(15,2) DEFAULT 0.00,
  `book_datetime` datetime DEFAULT NULL,
  `service_schedule_datetime` datetime DEFAULT NULL,
  `in_progress_datetime` datetime DEFAULT NULL,
  `completed_datetime` datetime DEFAULT NULL,
  `payment_datetime` datetime DEFAULT NULL,
  `point` int(10) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_idx` (`id`),
  KEY `fk_orders_order_status_id` (`order_status_id`),
  KEY `fk_orders_customer_id` (`customer_id`),
  KEY `fk_orders_user_vehicle_id` (`user_vehicle_id`),
  KEY `fk_orders_mechanic_id` (`mechanic_id`),
  KEY `fk_orders_partner_id` (`partner_id`),
  KEY `fk_orders_workshop_id` (`workshop_id`),
  KEY `fk_orders_coupon_code_id` (`coupon_code_id`),
  KEY `fk_vehicle_id` (`vehicle_id`),
  CONSTRAINT `fk_orders_coupon_code_id` FOREIGN KEY (`coupon_code_id`) REFERENCES `coupon_codes` (`id`),
  CONSTRAINT `fk_orders_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_mechanic_id` FOREIGN KEY (`mechanic_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_order_status_id` FOREIGN KEY (`order_status_id`) REFERENCES `order_statuses` (`id`),
  CONSTRAINT `fk_orders_partner_id` FOREIGN KEY (`partner_id`) REFERENCES `partners` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_user_vehicle_id` FOREIGN KEY (`user_vehicle_id`) REFERENCES `user_vehicles` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_workshop_id` FOREIGN KEY (`workshop_id`) REFERENCES `workshops` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_vehicle_id` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
