CREATE TABLE `workshops` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pb_workshop_code` varchar(10) DEFAULT NULL,
  `partner_id` int(10) unsigned NOT NULL,
  `postal_code_id` int(10) unsigned DEFAULT NULL,
  `branch_id` int(10) unsigned DEFAULT NULL,
  `workshop_key` varchar(16) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `time_offset` int(10) unsigned DEFAULT NULL,
  `maximum_service_capacity` int(10) unsigned DEFAULT 0,
  `average_rating` int(10) unsigned DEFAULT NULL,
  `is_emergency` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(10) DEFAULT 'active',
  `is_order` tinyint(1) DEFAULT 1,
  `is_emission_test` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_workshops_postal_code_id` (`postal_code_id`),
  KEY `fk_workshops_partner_id` (`partner_id`),
  KEY `fk_workshops_branch_id` (`branch_id`),
  CONSTRAINT `fk_workshops_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_workshops_partner_id` FOREIGN KEY (`partner_id`) REFERENCES `partners` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_workshops_postal_code_id` FOREIGN KEY (`postal_code_id`) REFERENCES `postal_codes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
