CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pb_product_code` varchar(10) DEFAULT NULL,
  `brand_id` int(10) unsigned NOT NULL,
  `product_category_id` int(10) unsigned DEFAULT NULL,
  `series` varchar(255) DEFAULT NULL,
  `price` decimal(15,2) NOT NULL,
  `special_price` decimal(15,2) DEFAULT NULL,
  `special_price_start_datetime` datetime DEFAULT NULL,
  `special_price_end_datetime` datetime DEFAULT NULL,
  `images` varchar(500) DEFAULT NULL,
  `thumbnail` varchar(500) DEFAULT NULL,
  `specification` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `warranty_period` int(10) unsigned DEFAULT NULL,
  `is_recommended` tinyint(1) DEFAULT 1,
  `status` int(10) unsigned DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `series_unique` (`series`),
  KEY `fk_products_brand_id` (`brand_id`),
  KEY `fk_products_product_category_id` (`product_category_id`),
  CONSTRAINT `fk_products_brand_id` FOREIGN KEY (`brand_id`) REFERENCES `product_brands` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
